
services:
  auth-service:
    build: ./backend/auth-service
    ports:
      - "3001:3000"
    environment:
      - DB_URL=mongodb+srv://sksv:sksvD@cluster0.zychm.mongodb.net/authDB?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - microservice-arch
    restart: always
    

  user-service:
    build: ./backend/user-service
    ports:
      - "3002:3000"
    environment:
      - DB_URL=mongodb+srv://sksv:sksvD@cluster0.zychm.mongodb.net/authDB?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - microservice-arch
    restart: always
    

  restaurant-service:
    build: ./backend/restaurant-service
    ports:
      - "3003:3000"
    environment:
      - MONGO_URI=mongodb+srv://sksv:sksvD@cluster0.zychm.mongodb.net/hotelDB?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - microservice-arch
    restart: always
    

  order-service:
    build: ./backend/order-service
    ports:
      - "3005:3000"
    environment:
      - MONGO_URI=mongodb+srv://sksv:sksvD@cluster0.zychm.mongodb.net/orderDB?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - microservice-arch
    restart: always
    

  payment-service:
    build: ./backend/payment-service
    ports:
      - "3006:3000"
    environment:
      - MONGO_URI=mongodb+srv://sksv:sksvD@cluster0.zychm.mongodb.net/authDB?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - microservice-arch
    restart: always
    

  delivery-service:
    build: ./backend/delivery-service
    ports:
      - "4001:4000"
    environment:
      - MONGO_URI=mongodb+srv://sksv:sksvD@cluster0.zychm.mongodb.net/authDB?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - microservice-arch
    restart: always
    

  notification-service:
    build: ./backend/notification-service
    ports:
      - "6001:6000"
    environment:
      - MONGO_URI=mongodb+srv://sksv:sksvD@cluster0.zychm.mongodb.net/notificationDB?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - microservice-arch
    restart: always
    

  search-service:
    build: ./backend/search-service
    ports:
      - "6002:6000"
    environment:
      - MONGO_URI=mongodb+srv://sksv:sksvD@cluster0.zychm.mongodb.net/userDB?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - microservice-arch
    restart: always
    

  review-service:
    build: ./backend/review-service
    ports:
      - "3004:3000"
    environment:
      - MONGO_URI=mongodb+srv://sksv:sksvD@cluster0.zychm.mongodb.net/review&feedbackDB?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - microservice-arch
    restart: always
    
networks:
  microservice-arch:
